spring:
  application:
    name: Pizzeria

  datasource:
    url: jdbc:postgresql://localhost:5432/pizzeria
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:

  flyway:
    enabled: true
    locations: classpath:db/migration

spring-doc:
  paths-to-match: "/**"
  swagger-ui:
    use-root-path: true
  # paths-to-match: "/api/**/v1/**"
